import Head from "next/head"
import ProductAddedToCart from "../components/ProductAddedToCart";
import Header from "../components/Header";
import { useSelector, useDispatch } from "react-redux";
import { emptyCart, selectedcartItems, selectTotal } from "../slices/cartSlice";
import {TbCurrencyNaira} from "react-icons/tb"
import { useRouter } from "next/navigation";
import { addToOrder } from "../slices/orderSlice";
import DesktopCart from "../components/DesktopCart";



function Cart() {
  const router = useRouter()
  const dispatch = useDispatch()
  const cartItems = useSelector(selectedcartItems);
  const cartTotal = useSelector(selectTotal)
  const checkoutHandler =  () => {
    dispatch(addToOrder(cartItems))
    router.push('/checkout')
    setTimeout(() => {
      dispatch(emptyCart())
    }, 3000);
  }
  if (cartItems.length === 0) {
    return (
      <>
      <Header /> 
      <div className='iceland mt-4 m-auto w-[95%] lg:max-w-5xl text-[#181818]'>
       <Head>
        <title>Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* fonts import */}
      </Head>
      
        <p className=' text-center text-3xl mt-10 h-[90vh]'>No porducts in cart</p>
      </div>
      </>
    );
  }
  return (
    <div className=''>
      <Header />
      <div className='pt-5 lg:grid grid-cols-3 gap-x-6 m-auto  lg:max-w-7xl  h-[calc(100vh-124px)] lg:h-full transition-all duration-500 ease-in overflow-y-scroll scrollbar-hide'>
        <div className="flex lg:hidden items-center justify-between  px-[12px] lg:px-0 text-gray-800 bg-white py-2 rounded-md">
          <div className="flex ">
            <p className="uppercase">subtotal </p>
            <p > - ({" "} {cartItems.length} {cartItems.length > 1 ? 
            'Products' : 
            'Product'} {" "} )</p>
          </div>
          <div>
            <p className="flex items-center "><TbCurrencyNaira  className="w-5 h-5 font-bold"/>{cartTotal.toLocaleString()}</p>
          </div>
        </div>
              <div className="col-span-2">

        <div className="hidden lg:flex items-center uppercase bg-gray-200 py-2 px-5 text-gray-700 text-sm font-poppins tracking-wider text-center">
        <div className="">
          <p><span className='hidden lg:inline-block'>PRODUCTS</span> </p>
        </div>
      
    </div>

        {/* {cartItems.map(
          ({ product, qty}) => (
            <ProductAddedToCart
            key={product.id}
            id={product.id}
            title={product.title}
            price={product.price}
            description={product.description}
            productQty={qty}
            image={product.image}
            />
            )
            )} */}
        {cartItems.map(
          ({ product, qty}) => (
            <DesktopCart
            key={product.id}
            id={product.id}
            title={product.title}
            price={product.price}
            description={product.description}
            productQty={qty}
            image={product.image}
            />
            )
            )}
      </div>
            <div className="">
            <div className="hidden lg:flex items-center uppercase bg-gray-200 py-2 px-5 text-gray-700 text-sm font-poppins tracking-wider text-center">
        <div className="">
          <p><span className='hidden lg:inline-block'>ORDER SUMMERY</span> </p>
        </div>
            </div>
          </div>
            </div>


      <div className="fixed left-0 bottom-0 px-3 shadow-xl w-full  text-lg bg-white z-10 pt-2 overflow-hiddentext-gray-500">
      <button className="capitalize w-[90%] h-[48px] rounded-md text-white  text-sm bg-yellow-500  mb-2 flex items-center justify-center m-auto " 
      onClick={checkoutHandler}>BuY Now | <TbCurrencyNaira  className="w-5 h-5"/>{cartTotal.toLocaleString()}
      </button>
          </div>
     </div>

  )
}

export default Cart

